gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed123_model/best_f1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed123_model/dev_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed123_model/result_dev.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed2021_model/best_f1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed2021_model/dev_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed2021_model/result_dev.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed27182_model/best_f1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed27182_model/dev_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed27182_model/result_dev.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed31415_model/best_f1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed31415_model/dev_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed31415_model/result_dev.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/best_f1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/dev_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/model/config.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/model/special_tokens_map.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/model/tokenizer_config.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/model/vocab.txt" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/result_dev.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/lingmess/alephbert-base_seed42_model/result_test.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_dev_e1.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_dev_e1.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_dev_e2.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_dev_e2.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_dev_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_dev_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_test_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/conll_logs/hebrew_aleph_test_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/test_eval.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed123/test_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_dev_e1.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_dev_e1.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_dev_e2.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_dev_e2.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_dev_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_dev_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_test_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/conll_logs/hebrew_aleph_test_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/test_eval.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed2021/test_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_dev_e1.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_dev_e1.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_dev_e2.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_dev_e2.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_dev_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_dev_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_test_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/conll_logs/hebrew_aleph_test_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/test_eval.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed27182/test_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_dev_e1.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_dev_e1.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_dev_e2.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_dev_e2.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_dev_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_dev_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_test_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/conll_logs/hebrew_aleph_test_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/test_eval.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed31415/test_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_dev_e1.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_dev_e1.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_dev_e2.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_dev_e2.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_dev_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_dev_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_test_e3.gold.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/conll_logs/hebrew_aleph_test_e3.pred.conll" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/test_eval.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/test_eval/doc_F1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/test_eval/overall_F1.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/test_eval_new.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/test_output.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/wlcoref/alephbert-base_seed42/test_output_new.json" -
gsutil cp "gs://p13n-asp-storage1/notebooks/jupyter/s0g0a87/Projects/neural-hebrew-coref/results/workspace_results_tree.txt" -
